### ISSUE TITLE
Support for Kendo DatePicker

### ISSUE THREAD

**Issue by programming-passion** [atata-framework/atata-kendoui#32]
Can we please add support for Kendo datepicker. It looks like we only have support for DateTimePicker at the moment

https://demos.telerik.com/kendo-ui/datepicker/index

**Comment by YevgeniyShunevych** [comment]
Sure, no problem. I created the [issue](https://github.com/atata-framework/atata-kendoui/issues/33) for that. Will try to implement in a week or two.

**Comment by programming-passion** [comment]
Thank you so much, Yevgeniy

**Comment by programming-passion** [comment]
Hello Yevgeniy - I tried using this Kendo DatePicker component. It looks like the .Set() method is only setting the year. Its not able to set the date and month. 

https://www.telerik.com/kendo-angular-ui/components/dateinputs/datepicker/

I also tried the SendKeys() function. It is also only setting the year, and ignores the day and month

**Comment by YevgeniyShunevych** [comment]
Hey. I see your issue and looking for a way to fix it. I should mention that I developed DatePicker for the jQuery version of Kendo UI. But Angular DatePicker component behaves a bit different and produces your issue.

**Comment by programming-passion** [comment]
Sounds good, Yevgeniy. I'll wait to hear from you.

**Comment by programming-passion** [comment]
Hello Yevgeniy,

Were you able to find a work-around for this?

Thank you for your help!

**Comment by YevgeniyShunevych** [comment]
Hey. I was trying to make `DatePicker` able to work with jQuery, Angular, React and Vue components, but it was not an easy thing, unfortunately. Their behavior is a bit different, so I had no luck to make a control universal. I would probably have to create a separate control for Angular `NgKendoDatePicker`, but I need time for it. For the upcoming 1-2 weeks, unfortunately, I can't ship it, as too many stuff I have currently to do.

If you are able to create a custom DatePicker control for your case, as a workaround, I would recommend to do it.

**Comment by YevgeniyShunevych** [comment]
You can inherit your control from `KendoDatePicker` and try to override `SetValue` method.

Here is the sample that you can try:

```cs
using System;
using OpenQA.Selenium;

namespace Atata.KendoUI
{
    public class NgKendoDatePicker<TOwner> : KendoDatePicker<TOwner>
        where TOwner : PageObject<TOwner>
    {
        protected override void SetValue(DateTime? value)
        {
            if (value == null)
            {
                AssociatedInput.Clear();
            }
            else
            {
                string valueAsString = value.Value.ToString("MMddyyyy");
                AssociatedInput.Set(Keys.Home + valueAsString);
            }
        }
    }
}
```

The first trick here is `ToString("MMddyyyy")` without slashes, as Angular automatically jumps to the next section.

The second one is `Keys.Home + valueAsString`. Otherwise, input starts in the middle of input, in the year section. So pressing `Home` key first.

**Comment by programming-passion** [comment]
Thanks much, Yevgeniy. This completely solved my problem!
