### ISSUE TITLE
Support for Kendo DateInput

### ISSUE THREAD

**Issue by programming-passion** [atata-framework/atata-kendoui#37]
Could we please add support for Kendo DateInput as well?
https://www.telerik.com/kendo-angular-ui/components/dateinputs/dateinput/

Our web application uses lot of date based entries, and having this added to atata.kendoUI would be greatly helpful

Regards,

**Comment by YevgeniyShunevych** [comment]
I thought that regular Atata `DateInput<TOnwer>` will work OK with Kendo DateInput. But after some testing, unfortunately, it is not. Will try to add an extra component in a week or two.

**Comment by programming-passion** [comment]
Appreciate your help, Yevgeniy

**Comment by YevgeniyShunevych** [comment]
I've added `KendoDateInput<TOwner>` and `NgKendoDateInput<TOwner>` controls in recently release Atata.KendoUI 1.2.0. You can verify your Angular Kendo DateInput with `NgKendoDateInput<TOwner>` control.
