### ISSUE TITLE
KendoDropdownList not able to select the item after clicking on it

### ISSUE THREAD

**Issue by programming-passion** [atata-framework/atata-kendoui#39]
Hello Yevgeniy,

I used KendoDropdownList Component and attempted to select a value using Set().
It looks like it's clicking on the dropdown. However it fails to select the item.

https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/

Is this a known issue?

Thanks,

**Comment by YevgeniyShunevych** [comment]
Hi,

I was able to successfully test `KendoDropDownList` against the drop-down located on https://www.telerik.com/kendo-angular-ui/components/dropdowns/dropdownlist/

Could you please provide details of your error?

**Comment by programming-passion** [comment]
Hello Yevgeniy,

When I manually click on the KendoDropDownList, I see that the following element shows up
![image](https://user-images.githubusercontent.com/845885/67998436-e740f580-fc2e-11e9-8adc-affc0c667592.png)

When I attempt to select a value using Set(), I see the following error

![image](https://user-images.githubusercontent.com/845885/67998465-063f8780-fc2f-11e9-8372-04dde7e6640b.png)

Stack Trace:
![image](https://user-images.githubusercontent.com/845885/67998469-0b9cd200-fc2f-11e9-9150-33701b88c066.png)

**Comment by YevgeniyShunevych** [comment]
Hey,

It's a bit strange that Atata cannot find `.k-popup` element. I double checked Kendo Angular DropDownList and it has it:

```html
<kendo-popup class="k-animation-container k-animation-container-shown" dir="ltr" style="left: 30px; top: 91px; min-width: 174px; width: 174px; height: auto;">
  <div class="k-popup k-list-container k-reset">
    <kendo-list>
    <!-- ... -->
    </kendo-list>
  </div>
</kendo-popup>
```

It may be that you have drop-down customized or of a specific version. Could you please expand your `<kendo-popup>` element, which is shown in your screenshot, and share its child HTML element. Curious if it has `<div class="k-popup k-list-container k-reset">` or something else. Anyway, we will find some solution.

**Comment by SivaATF** [comment]
I'm also not able to set a dropdown value using Atata kendo Dropdown list.

I'm using Kendo UI MVC version 2018.1.117.

 OpenQA.Selenium.NoSuchElementException : Unable to locate visible element:
    - By.XPath: .//*[normalize-space(@id) = 'GroupSelectList']/descendant-or-self::*[contains(concat(' ', normalize-space(@class), ' '), ' k-dropdown ')]
    - Search time: 5.005s
    - Search options: {Visibility=Visible, Timeout=5s, RetryInterval=0.5s, IsSafely=False}

**Comment by programming-passion** [comment]
Hello Yevgeniy,

Here's the expanded <kendo-popup> you had asked for.  

Appreciate your help!

![image](https://user-images.githubusercontent.com/845885/68355124-4645b500-00dc-11ea-83ff-26e6decdd14b.png)

**Comment by YevgeniyShunevych** [comment]
I made a change in recently release Atata.KendoUI 1.2.0 for `KendoDropdownList`. You can verify if your issue still persists.
