### ISSUE TITLE
Kendo Grid: Any option to sort a column ASC and DESC

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata-kendoui#41]
I'm looking for sorting the kendo grid column by ASC and DESC. I was trying to read the Header property, but could not make the entire table to sort.

.ListGrid.Should.BeVisible()
                .ListGrid.Headers[x => x.Name == "Id"].SortDesc()
                .ListGrid.Should.BeVisible()

Thanks in advance.

**Comment by YevgeniyShunevych** [comment]
It is implemented in v1.3.0 version.

Issue: #56 Add column header sorting to KendoGrid.
