### ISSUE TITLE
Support for Kendo Auto Complete

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata-kendoui#42]
Could you please guide on supporting Kendo Auto Complete control?

Thank you.

**Comment by YevgeniyShunevych** [comment]
`KendoAutoComplete` is added in v1.3.0 version.

Issues:
- #57 Add KendoAutoComplete<T, TOwner> and KendoAutoComplete<TOwner> controls.
- #58 Add ReactKendoAutoComplete<T, TOwner> and ReactKendoAutoComplete<TOwner> controls.
