### ISSUE TITLE
Question: Does kendo grid support to select by property name

### ISSUE THREAD

**Issue by SivaATF** [atata-framework/atata-kendoui#5]
Hello,

I'm trying to select row in a kendo grid using the property value equals some value. Can you please help on how i can do that?

Thanks.

**Comment by YevgeniyShunevych** [comment]
Please check [Table component](https://atata-framework.github.io/components/#table). As `KendoGrid` inherits `Table`, the approaches are similar.

Here is a sample, for case when you need to find rows by cell value:

```cs
using Atata;
using Atata.KendoUI;

namespace SampleApp.UITests
{
    using _ = SamplePage;

    public class SamplePage : Page<_>
    {
        public KendoGrid<ItemRow, _> Grid { get; private set; }

        public class ItemRow : KendoGridRow<_>
        {
            public Text<_> Name { get; private set; }

            public Number<_> Amount { get; private set; }

            // etc...
        }
    }
}
```

And in test method:

```cs
Go.To<SamplePage>().
    Grid.Rows[x => x.Name == "Item 1"].Amount.Should.Equal(5);
```

Is it what you were looking for?

**Comment by SivaATF** [comment]
I tried using the same approach, but it always says no such element exception.

The grid contains around 12 rows and i'm trying to select a row based on cell value.

.SearchResults.Rows[x=> x.FullName== "XXXX, XXX"]

OpenQA.Selenium.NoSuchElementException : Unable to locate element: Full Name
Context element:
Tag: tr
Location: {X=242,Y=713}
Size: {Width=1208, Height=34}
Text: XXXX XXXXX XXXX, XXX

The exception text shows only the row data and not the column name , column text.

**Comment by YevgeniyShunevych** [comment]
I see. By default cell is searched by grid column header. In your case it was looking for "Full Name" column header. If you have different name you can try:

```cs
public class ItemRow : KendoGridRow<_>
{
    [FindByColumnHeader("Custom Fullname")]
    public Text<_> FullName { get; private set; }
}
```

Or you can also use `FindByColumnIndex` passing the column index:

```cs
public class ItemRow : KendoGridRow<_>
{
    [FindByColumnIndex(0)]
    public Text<_> FullName { get; private set; }
}
```

**Comment by SivaATF** [comment]
Awesome!!! FindByColumnHeader worked like charm. Thanks for the quick replies.
